// yt-dlp subtitle/caption detection and download for the "Vídeo y Audio"
// URL transcription flow (Desktop-only). Order of preference, per spec:
//   1. Manual (human-authored) subtitles
//   2. Automatic (ASR-generated by the provider) captions
//   3. No subtitles at all -> caller falls back to audio-only download + Whisper
//
// Never downloads full video when only audio/subtitles are needed.

import fs from "fs";
import path from "path";
import { CONFIG } from "../config";
import { resolveMacAwareBinary } from "../binary-resolution";
import { getYtdlpCommonArgs } from "./command-builder";
import { ProcessRunner } from "../infrastructure/processes/process-runner";

export function findYtdlpBinary(): string {
  const configured = CONFIG.media.binaries.ytdlp;
  if (!configured || configured === "yt-dlp") return resolveMacAwareBinary("yt-dlp");
  return configured;
}

export interface SubtitleTrackInfo {
  lang: string;
  formats: string[];
}

export interface UrlCaptionInfo {
  title: string;
  durationSeconds: number | null;
  manual: SubtitleTrackInfo[];
  automatic: SubtitleTrackInfo[];
}

interface YtdlpJsonSubtitleEntry {
  ext: string;
}

interface YtdlpJsonResult {
  title?: string;
  duration?: number;
  subtitles?: Record<string, YtdlpJsonSubtitleEntry[]>;
  automatic_captions?: Record<string, YtdlpJsonSubtitleEntry[]>;
}

function toTrackList(dict: Record<string, YtdlpJsonSubtitleEntry[]> | undefined): SubtitleTrackInfo[] {
  if (!dict) return [];
  return Object.entries(dict)
    .map(([lang, entries]) => ({ lang, formats: Array.from(new Set(entries.map((e) => e.ext))) }))
    .sort((a, b) => a.lang.localeCompare(b.lang));
}

/** Lists manual/automatic caption availability without downloading anything. */
export async function probeUrlCaptions(url: string, timeoutMs = 30_000, signal?: AbortSignal): Promise<UrlCaptionInfo> {
  const runner = new ProcessRunner(findYtdlpBinary(), timeoutMs);
  const args = [...getYtdlpCommonArgs(false), "--skip-download", "-J", url];
  const result = await runner.run({ args, timeoutMs, signal });

  if (result.exitCode !== 0) {
    throw new Error(result.stderr.slice(0, 500) || `yt-dlp exit ${result.exitCode}`);
  }

  let parsed: YtdlpJsonResult;
  try {
    parsed = JSON.parse(result.stdout);
  } catch {
    throw new Error("No se pudo interpretar la respuesta de yt-dlp.");
  }

  return {
    title: parsed.title ?? url,
    durationSeconds: typeof parsed.duration === "number" ? parsed.duration : null,
    manual: toTrackList(parsed.subtitles),
    automatic: toTrackList(parsed.automatic_captions),
  };
}

export interface DownloadedSubtitle {
  srtPath: string;
  lang: string;
  kind: "manual" | "automatic";
}

/**
 * Downloads one subtitle track (manual or automatic) and normalizes it to
 * SRT via yt-dlp's own --convert-subs (uses FFmpeg internally — already a
 * required dependency of this app). No video/audio is downloaded.
 */
export async function downloadUrlSubtitle(
  url: string,
  lang: string,
  kind: "manual" | "automatic",
  outDir: string,
  timeoutMs = 60_000,
  signal?: AbortSignal
): Promise<DownloadedSubtitle> {
  fs.mkdirSync(outDir, { recursive: true });
  const outTemplate = path.join(outDir, "subtitle.%(ext)s");
  const runner = new ProcessRunner(findYtdlpBinary(), timeoutMs);
  const args = [
    ...getYtdlpCommonArgs(false),
    "--skip-download",
    kind === "manual" ? "--write-subs" : "--write-auto-subs",
    "--sub-langs", lang,
    "--convert-subs", "srt",
    "-o", outTemplate,
    url,
  ];
  const result = await runner.run({ args, timeoutMs, signal });
  const srtPath = path.join(outDir, `subtitle.${lang}.srt`);
  if (result.exitCode !== 0 || !fs.existsSync(srtPath)) {
    throw new Error(result.stderr.slice(0, 500) || "yt-dlp no generó el archivo de subtítulos.");
  }
  return { srtPath, lang, kind };
}

// Semantic yt-dlp format selectors — never a rigid provider-specific format
// id (those change over time and vary per-video, see download-strategy.ts's
// own reasoning for the main YouTube pipeline). Two attempts: a plain
// "best audio available" selector, then an alternate-codec/container
// selector as a fallback if the first representation is unavailable or
// rejected (e.g. a per-format 403) — same spirit as the recoverable-403
// candidate fallback already used elsewhere in this app, simplified since
// the only requirement here is "decodable audio for Whisper", not a
// specific output container.
const AUDIO_ONLY_CANDIDATES = [
  "bestaudio/best",
  "bestaudio[ext=webm]/bestaudio[acodec=opus]/best",
] as const;

export interface AudioDownloadResult {
  candidateIndex: number;
  formatSelector: string;
}

/**
 * Downloads audio only (no video track) to a WAV file — the fallback path
 * when a URL has no subtitles and the user wants a local Whisper
 * transcription instead. Tries each candidate selector in order; only
 * throws once all candidates have failed.
 */
export async function downloadUrlAudioOnly(
  url: string,
  outputWavPath: string,
  timeoutMs = 300_000,
  signal?: AbortSignal
): Promise<AudioDownloadResult> {
  fs.mkdirSync(path.dirname(outputWavPath), { recursive: true });
  const runner = new ProcessRunner(findYtdlpBinary(), timeoutMs);

  let lastError = "No se pudo descargar el audio de la URL.";
  for (let i = 0; i < AUDIO_ONLY_CANDIDATES.length; i++) {
    if (signal?.aborted) throw new Error("Process cancelled");
    const formatSelector = AUDIO_ONLY_CANDIDATES[i];
    const args = [
      ...getYtdlpCommonArgs(false),
      "-f", formatSelector,
      "--extract-audio",
      "--audio-format", "wav",
      "-o", outputWavPath,
      url,
    ];
    const result = await runner.run({ args, timeoutMs, signal });
    if (result.exitCode === 0 && fs.existsSync(outputWavPath)) {
      return { candidateIndex: i, formatSelector };
    }
    lastError = result.stderr.slice(0, 500) || lastError;
  }
  throw new Error(lastError);
}
